\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

\section{Introduction}
\subsection{Definition of masting}
\begin{enumerate}
\item Observations of masting in relation to seed predation and flowering
\end{enumerate}
\subsection{Different hypotheses operating at different reproductive stages like filters}
\begin{enumerate}
\item Pollination success (Pollination coupling)
\item Resources availability (Resource Matching)
\item Dispersal (Predation satiation)
\end{enumerate}
\subsection{Why traits can help link hypotheses to masting mechanisms}
\begin{enumerate}
\item Mechanisms might not be mutually exclusive, but some might be stronger than the other for certain species
\item Traits thus can be important to understand masting through their relative importance
\end{enumerate}
\subsection{Trait-based perspective}
\begin{enumerate}
\item Literature review on understanding masting from traits perspective 
\begin{enumerate}
\item Wind pollination is related to higher CV
\item Animal dispersed seeds have higher CV than wind dispersed seeds
\item Larger seed is associate with higher CV
\item Recent papers also focus on resource perspective using leaf and shoot traits
\end{enumerate}
\item Existing studies mainly trying to find relations between different traits and masting.
\item Not clear connection between traits and hypotheses and potential evolutionary drivers
\end{enumerate}
\subsection{Introduce framework linking hypothesis x traits x masting}
\begin{enumerate}
\item Link traits to hypotheses help understand drivers of masting for different species
\item Especially when consider whether the evolutionary drivers are more similar for clades those are closely related.
\end{enumerate}
\subsection{Use data from one specific geographical region}
\begin{enumerate}
\item Here we use North American tree data to test this framework since they have information on their life-history
\begin{enumerate}
\item Masting info available
\item Includes both masting and non-masting species
\item Not using CV data because don't have stand-level traits data
\end{enumerate}
\end{enumerate}

\section{Discussion}
\subsection{Summary of main findings}
\begin{enumerate}
\item Pollination supports the pollination coupling hypothesis
\item Seed weight supports the predation satiation hypothesis
\item These act at the start and the end of the reproductive cycle, provide evolutionary incentive, which I will explain below
\item Discuss mechanisms in the context of existing literature
\begin{enumerate}
\item Previous literature on seed mass and masting think from the resource depletion perspective (Bigger seeds use up resources so cannot reproduce every year)
\item However, from evolutionary perspective, seeds attractive to animal dispersers will benefit more from masting
%Maybe I can try to subset wind dispersed and animal dispersed species and see if this relationship between seed weight and masting is stronger for animal dispersed species!
\end{enumerate}
\item Other traits show some pattern but statistically non-significant
\item Transition to alternative hypotheses
\end{enumerate}
\subsection{Masting is a population-level phenomenon}
\begin{enumerate}
\item Other traits may matter to masting below the species level, like population level
\item Examples of species that mast only under certain environmental conditions (E.g., \textit{Hymenaea coubaril})
\item Traits need to be measured locally and match with masting data
\end{enumerate}
\subsection{Different species selected under different hypotheses}
\begin{enumerate}
\item Introduce flowering masting vs. seed masting
\item Different species driven by different mechanisms
\item Need a more refined definition of masting and additional flowering-related traits
\item Transition to phylogeny
\end{enumerate}
\subsection{Evolutionary scale} %emw25May2026 -- at some point we may want to make the point that basically we think these relationships may appear at different scales -- either below the population level or while controlling for deep evolutionary time... 
\begin{enumerate}
\item Angiosperm vs. gymnosperm results
\begin{enumerate}
%emw25May2026 -- can you connect for me what the below means? What point do you want to make here? 
\item More masting gymnosperm sp
\item Longer leaf longevity in gymnosperm
\item More monoecious species in gymnosperm
\item Wind pollination is universal among gymnosperms
\item Gymnosperm and angiosperm have distinct trait space occupancy
\item Importance of looking for potential evolution support between gymnosperm and angiosperm
\begin{enumerate}
\item Test if masting was gradually diluted in angiosperm as they transitioned to biotic pollination and faster life histories
\end{enumerate}
\end{enumerate}
%emw25May2026 -- I think the below two points are their own subsection and you should refer back to the literature here (you could start adding citations to the outline)
\item Many traits have strong phylogenetic signal, it is hard to tease out traits from masting, which limits the inference
\item Data is strongly nested in phylogeny, and data is sparse.
%emw25May2026 -- I see the below as a full section on future pathways or at least a paragraph ... do you have more to say here?
\item Importance of testing within clades and collect more data (\textit{Quercus.})
\end{enumerate}
\end{document}



\subsection{Definetly include}
\begin{enumerate}
\item Define masting
\item Introduce different hypotheses related to masting
\item Introduce that different hypotheses act on different stages of the reproductive process (e.g., flowering, pollination, seed maturation, dispersal)
\item Existing studies regarding functional traits and masting found: 
  \begin{enumerate}
  \item High CV is common in species with high stem tissue density
  \item Short-lived leaves with low LMA is associate with low CV
  \item Large seed is associate with high CV
  \item floral transition is associate with year-to-year variability
  \item wind pollination is associate with hight CV
  \end{enumerate}
\item Existing studies lack emphasis on the role of reproductive traits as mechanistic links between masting and hypotheses.
\item Especially on relationship between seed mass and masting focus on an ecological constraint perspective, where seed mass reflects the cost of reproduction. However, we try to capture the evolutionary mechanisms underlying masting benefits. For masting to be adaptive under the predator satiation hypothesis, seeds must be consumed by animals. Therefore, fruit size might be more relevant than seed mass alone.
\item Our study propose a framework connecting:
\begin{enumerate}
\item reproductive traits
\item stages of reproduction
\item specific masting hypotheses
\end{enumerate}

\item This framework can clarify which traits are under selection in masting species


\end{enumerate}

\section{Discussion}
\subsection{Definetly include}
\begin{enumerate}
\item Seed mass and wind pollination are reproductive traits significantly associated with masting patterns. This might suggest that reproductive allocation plays a key role in shaping masting behavior, supporting predation satiation hypothesis and pollination coupling hypothesis. 
\item However, the fact that we didn't find relationships with other traits indicates that trait-based explanations alone are not sufficient to fully explain masting.
\item \textbf{Gymnosperm are more likely to be masting species}, (is there a possibility that masting might be an ancestral strategy that becomes lost in some angiosperm lineages later?)
\item We found moderate phylogenetic signal for masting in both gymnosperms and angiosperms, which align with other people's finding (e.g.,: Pearse et al., 2020, found a modest phylogenetic signal in CVp), then link to next point.
\item \textbf{Masting is strongly related to environment as well}, some species might be exhibit masting or not depending on the environment they are in, broad trait-based analysis do not capture environmental drivers, and that's the reason why we can't use any masting metrics capturing other characteristics of masting.
\item Different hypotheses may act at different stages (for flower masting and seed masting species), playing the selection on different species, need better data on flowering traits and finer resolution on masting definition.
\item Existence of clear counterexamples especially within the clade. Focusing on within-clade variation (oaks) may be more informative. Need more detailed monitoring on masting pattern and reproductive traits for more species in oak family, potentially with data for same species in different environment.
\end{enumerate}
\section{Methods} %emw25May2026 --- skipping now that we're writing it!
\subsection{Data collection}
\begin{enumerate}
\item Data scraping
  \begin{enumerate}
  \item Trait selection
  \item Data sources: Silvics of North America, Kew Seed Dataset, TRY Dataset
  \item Keywords used for data scraping
  \begin{enumerate}
  \item Definition of strong masting vs. non-masting (referred to as masting vs. non-masting moving forward)
  \item Criteria for other traits
  \end{enumerate}
  \end{enumerate}
\item Data cleaning
  \begin{enumerate}
  \item Cleaning of categorical traits
  \item Decision for numeric traits with a range
  \end{enumerate}
\end {enumerate}
\subsection{Statistical analysis}
  \begin{enumerate}
  \item Main analysis for masting pattern and single trait: phyloglm
  \item Masting pattern with a multivariate analysis: NMDS
  \item Phylogenetic signal check for traits: Pagel's $\lambda$ and D-statistics
  \end{enumerate}