\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

\section{Introduction}
\subsection{Observations of masting in relation to seed predation and flowering}
\begin{itemize}
\item Definition of masting
\end{itemize}
\subsection{Major hypotheses for masting}
\subsection{Hypotheses operating at different reproductive stages}
\begin{itemize}
\item Predation satiation—seed maturation/dispersal stages
\item Pollination coupling—flowering/pollination stages
\item Resource matching—across stages
\item Mechanisms are not mutually exclusive
\end{itemize}
\subsection{Trait-based perspective}
\begin{itemize}
\item Literature review on masting and functionaltraits
\item Briefly connect traits to mechanisms
\item Shift focus from seed and pollination-related hypotheses toward resource-matching oriented mechanisms
\end{itemize}
\subsection{Introduce framework linking hypothesis x traits x masting}
\begin{itemize}
\item Here we use North American tree data to test this framework
\begin{itemize}
\item Masting info available
\item Includes both masting and non-masting species
\end{itemize}
\end{itemize}
\section{Methods}
\subsection{Data collection}
\begin{itemize}
\item Data scraping
  \begin{itemize}
  \item Data sources: Silvics of North America, Kew Seed Dataset, TRY Dataset
  \item Trait selection
  \item Keywords used for data scraping
  \begin{itemize}
  \item Definition of strong masting vs. non-masting (referred to as masting vs. non-masting moving forward)
  \item Criteria for other traits
  \end{itemize}
  \end{itemize}
\item Data cleaning
  \begin{itemize}
  \item Cleaning of categorical traits
  \item Decision for numeric traits with a range
  \end{itemize}
\end {itemize}
\subsection{Statistical analysis}
  \begin{itemize}
  \item Main analysis for masting pattern and single trait: phyloglm
  \item Masting pattern with a multivariate analysis: NMDS
  \item Phylogenetic signal check for traits: Pagel's $\lambda$ and D-statistics
  \end{itemize}
\section{Discussion}
\subsection{Summary of main findings}
\begin{itemize}
\item Seed weight supports the predation satiation hypothesis
\item Pollination supports the pollination coupling hypothesis
\item Discuss mechanisms in the context of existing literature
\item Transition to alternative hypotheses
\end{itemize}
\subsection{Masting is a population-level phenomenon}
\begin{itemize}
\item Examples of species that mast only under certain environmental conditions
\item Traits need to be measured locally
\end{itemize}
\subsection{Different species selected under different hypotheses}
\begin{itemize}
\item Introduce flowering masting vs. seed masting
\item Different species driven by different mechanisms
\item Need a more refined definition of masting and additional flowering-related traits
\item Transition to phylogeny
\end{itemize}
\subsection{Evolutionary scale}
\begin{itemize}
\item Angiosperm vs. gymnosperm results
\begin{itemize}
\item More masting gymnosperm sp
\item Longer leaf longevity in gymnosperm sp
\item Wind pollination is universal among gymnosperms
\end{itemize}
\item Importance of testing within clades (\textit{Quercus.})
\end{itemize}
\end{document}
\subsection{Definetly include}
\begin{itemize}
\item Define masting
\item Introduce different hypotheses related to masting
\item Introduce that different hypotheses act on different stages of the reproductive process (e.g., flowering, pollination, seed maturation, dispersal)
\item Existing studies regarding functional traits and masting found: 
  \begin{itemize}
  \item High CV is common in species with high stem tissue density
  \item Short-lived leaves with low LMA is associate with low CV
  \item Large seed is associate with high CV
  \item floral transition is associate with year-to-year variability
  \item wind pollination is associate with hight CV
  \end{itemize}
\item Existing studies lack emphasis on the role of reproductive traits as mechanistic links between masting and hypotheses.
\item Especially on relationship between seed mass and masting focus on an ecological constraint perspective, where seed mass reflects the cost of reproduction. However, we try to capture the evolutionary mechanisms underlying masting benefits. For masting to be adaptive under the predator satiation hypothesis, seeds must be consumed by animals. Therefore, fruit size might be more relevant than seed mass alone.
\item Our study propose a framework connecting:
\begin{itemize}
\item reproductive traits
\item stages of reproduction
\item specific masting hypotheses
\end{itemize}

\item This framework can clarify which traits are under selection in masting species


\end{itemize}

\section{Discussion}
\subsection{Definetly include}
\begin{itemize}
\item Seed mass and wind pollination are reproductive traits significantly associated with masting patterns. This might suggest that reproductive allocation plays a key role in shaping masting behavior, supporting predation satiation hypothesis and pollination coupling hypothesis. 
\item However, the fact that we didn't find relationships with other traits indicates that trait-based explanations alone are not sufficient to fully explain masting.
\item \textbf{Gymnosperm are more likely to be masting species}, (is there a possibility that masting might be an ancestral strategy that becomes lost in some angiosperm lineages later?)
\item We found moderate phylogenetic signal for masting in both gymnosperms and angiosperms, which align with other people's finding (e.g.,: Pearse et al., 2020, found a modest phylogenetic signal in CVp), then link to next point.
\item \textbf{Masting is strongly related to environment as well}, some species might be exhibit masting or not depending on the environment they are in, broad trait-based analysis do not capture environmental drivers, and that's the reason why we can't use any masting metrics capturing other characteristics of masting.
\item Different hypotheses may act at different stages (for flower masting and seed masting species), playing the selection on different species, need better data on flowering traits and finer resolution on masting definition.
\item Existence of clear counterexamples especially within the clade. Focusing on within-clade variation (oaks) may be more informative. Need more detailed monitoring on masting pattern and reproductive traits for more species in oak family, potentially with data for same species in different environment.
\end{itemize}