\documentclass{article}
\usepackage{Sweave}
\usepackage{float}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{pdflscape}
\usepackage{hyperref}
\usepackage{indentfirst}
\usepackage[top=1.0in, bottom=1.0in, left=1.1in, right=1.1in]{geometry}
\usepackage[utf8]{inputenc}

\title{Mast-Trait}
\author{Xiaomao Wang}

\begin{document}
\SweaveOpts{concordance=FALSE}

<<load-plots,echo=FALSE,results=hide,warning=FALSE,message=FALSE>>=
source("C:/PhD/Project/PhD_thesis/mast_trait/analyses/nmds.R")
source("C:/PhD/Project/PhD_thesis/mast_trait/analyses/phyo.R")
source("C:/PhD/Project/PhD_thesis/mast_trait/analyses/glm.R")
@

%emw16Jun: Nice work! This is feeling closer. I think now we should indicate what is supp and what will be main text, so can you indicate here what will be in the supp for tables and figures? Those should all come AFTER the main text figures, and eventually should go in a supp file. Also we should start moving towards captions we could send to a journal. See also my comments throughout with: %emw16Jun
\section{Results}
\begin{enumerate}
\item Gathered data
\begin{enumerate}
\item Structure of data from Silvics
\begin{enumerate}
<<setup, echo=FALSE>>=
angio_n <- length(angio$latbi)
N_angio <- 124
N_angio_mast <- sum(angio$mastEvent == "1", na.rm = TRUE)
angio_sum <- paste0(round(100 * angio_n/N_angio),
  "\\% (",
  angio_n,
  "/",
  N_angio,
  ")"
)
angio_mast <- paste0(round(100 * N_angio_mast/angio_n),
  "\\% (",
  N_angio_mast,
  "/",
  angio_n,
  ")"
)

gymno_n <- length(conifer$latbi)
N_gymno <- 64
N_gymno_mast <- sum(conifer$mastEvent == "1", na.rm = TRUE)
gymno_sum <- paste0(round(100 * gymno_n/N_gymno),
  "\\% (",
  gymno_n,
  "/",
  N_gymno,
  ")"
)
gymno_mast <- paste0(round(100 * N_gymno_mast/gymno_n),
  "\\% (",
  N_gymno_mast,
  "/",
  gymno_n,
  ")"
)

fix_unicode <- function(x) {
  x <- gsub("\u2212", "-", x)
  x <- gsub("–", "-", x)
  x <- gsub("—", "-", x)
  x <- gsub("%", "\\\\%", x)
  x <- gsub("\\balpha\\b", "$\\\\alpha$", x)
  x <- gsub("\\blambda\\b", "$\\\\lambda$", x)
  x
}

angio_results[] <- lapply(angio_results, function(x) {
  if (is.character(x))
    fix_unicode(x)
  else
    x
})

colnames(angio_results) <-
    fix_unicode(colnames(angio_results))

conifer_results[] <- lapply(conifer_results, function(x) {
  if (is.character(x))
    fix_unicode(x)
  else
    x
})

colnames(conifer_results) <-
    fix_unicode(colnames(conifer_results))


@

\item Angiosperm \Sexpr{gsub("%", "\\\\%", angio_sum)} with masting data; Masting and non-masting split almost equally \Sexpr{gsub("%", "\\\\%", angio_mast)}; Gymnosperm \Sexpr{gsub("%", "\\\\%", gymno_sum)} with masting data; almost all species are masting \Sexpr{gsub("%", "\\\\%", gymno_mast)}
\end{enumerate}

\item Number of traits for different hypotheses
\begin{enumerate}
\item For angiosperm, we have data for:
\begin{enumerate}
\item Predator satiation: seed weight, fruit size, oil content, seed dispersal mode, seed dormancy
\item Pollination coupling: pollination mode, reproductive type
\item Resource matching: drought tolerance, leaf longevity
\end{enumerate}
\item For gymnosperm, we have the same data as for angiosperm, but we only have oil content for masting species and all the gymnosperm species are wind pollinated.
\end{enumerate}
\end{enumerate}


\newgeometry{margin=1cm}
\begin{figure}[p]
\centering
\includegraphics[width=\textwidth, height=0.8\textheight]{../output/figures/rawDataWithStatsAngio.pdf}
\caption{How plant traits related to different hypotheses differ in masting and non-masting for angiosperm species: We show data for traits related to the predator satiation hypothesis (a-e), pollination coupling hypothesis (f-g) and the resource matching hypothesis (h-i) as either violin plots (1-c, i) or proportional histograms (d-h) separated by species categorized as masting (red) or non-masting (green). We show model summaries only where significant (P-value < 0.5) and also report the model sample size (N), regression coefficient (Estimate), and phylogenetic signal parameter $\alpha$. Full model results are show in supp Table 1.}
\label{fig:rawangio}
\end{figure}

\begin{figure}[p]
\centering
\includegraphics[width=\textwidth,height=0.8\textheight]{../output/figures/rawDataWithStatsCon.pdf}
\caption{How plant traits related to different hypotheses differ in masting and non-masting for gymnosperm species: We show data for traits related to the predator satiation hypothesis (a-e), pollination coupling hypothesis (f-g) and the resource matching hypothesis (h-i) as either violin plots (1-c, i) or proportional histograms (d-h) separated by species categorized as masting (red) or non-masting (green). We show model summaries only where significant (P-value < 0.5) and also report the model sample size (N), regression coefficient (Estimate), and phylogenetic signal parameter alpha. Full model results are show in supp Table 2.}
\label{fig:rawcon}
\end{figure}
\restoregeometry
\newpage

\begin{figure}[H]
\centering
\includegraphics[width=0.8\textwidth]{../output/figures/modelFitSeedWeight.pdf}
\caption{Predicted likelihood of masting as a function of seed weight for all angiosperm species (solid red line) and the biotic-dispersed subgroup (dashed green line), estimated using phylogenetic logistic regression. Individual species observations are plotted as binary data points at 0 (non-masting) and 1 (masting).}
\label{fig:seedweight}
\end{figure}

\item Results for each hypothesis
\begin{enumerate}
\item Predation satiation: seed weight only with a small effect and only for angiosperm
\begin{enumerate}
\item Only seed weight is related to masting with larger seeds increasing the probability of being a masting species (Figure (\ref{fig:rawangio})). For angiosperms only, tripling of seed weight (from a median seed weight of 90.9g to 272.7g) is predicted to increase the likelihood of masting from 0.45 to 0.51 (Figure (\ref{fig:seedweight})).
And this increase is stronger in biotic-dispersed seed group, tripling of seed weight (from a median seed weight of 1087.15g to 3261.45g) is predicted to increase the likelihood of masting from 0.72 to 0.80 (Table (\ref{tab:regressionseed}); Figure (\ref{fig:seedweight})). 

\end{enumerate}
\item Pollination satiation: wind pollination for angiosperm
\begin{enumerate}
\item we found wind pollination is related to masting for angiosperm species, likelihood for wind-pollinated species is predicted to increase the likelihood of masting to 0.62, whereas the likelihood is 0.20 for animal-pollinated species.
of being strong masting species. Gymnosperm are all wind pollinated, and gymnosperm has a greater portion of masting species (89\% (54/61)).
\end{enumerate}
\item Resource matching: nothing significant

\end{enumerate}
\newpage
% ------------------------------------------
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/nmdsFinal_scalearea.pdf}
\caption{Non-metric multidimensional scaling (NMDS) of trait composition for angiosperm and gymnosperm species. Each point represents a species, with position determined by NMDS axes. Points are colored by drought tolerance, filled by masting or not, shaped by reproductive type, sized by seed weight. Panels are arranged as (a) angiosperm NMDS1–NMDS2, (b) angiosperm NMDS2–NMDS3, (c) gymnosperm NMDS1–NMDS2, and (d) gymnosperm NMDS2–NMDS3.}
\label{fig:nmds}
\end{figure}

\item Multidimension-NMDS
\begin{enumerate}
\item No strong trend when considering single trait, maybe because it happens in multidimensional space
\begin{enumerate} 
\item Masting is not aligned well along any axis in the NMDS analysis.
\item We do not have evidence that the combination of traits for any of the hypotheses is driving the pattern of masting.
\end{enumerate}
\end{enumerate}
% ------------------------------------------
\newgeometry{margin=1cm}
\begin{figure}[p]
\centering
\includegraphics[width=\textwidth,height=0.9\textheight,keepaspectratio]{../output/figures/weightTreeConceptual2.jpg}
\caption{Phylogenetic tree for all angioperm species included in the analysis. The color scheme of the branch is the trait value for seed weight (log). The color tip is colored by masting or not. The other traits are labeled after the tip labels with different color and size. We also show the predictions of relationship between traits and masting. We calculated the Pagel's $\lambda$ for continuous traits as well as multilevel categorical traits, and calculated D-statistic for binary traits}
\label{fig:coneptangio}
\end{figure}
\restoregeometry
\newpage
% ------------------------------------------

\item Phylogenetic patterns
\begin{enumerate}
\item Pagel's $\lambda$ for continuous traits and multilevel categorical traits in Table \ref{tab:lambda}, D-statistic for binary traits in Table \ref{tab:d}.
\begin{enumerate}
\item Masting shows a moderate phylogenetic signal in both gymnosperms (estimated D = 0.51) and angiosperms (estimated D = 0.58) (Table \ref{tab:d}).
\item Seed weight has strong phylogenetic signal for both angiosperm ($\lambda$ = 0.95) and gymnosperm ($\lambda$ = 0.97). We can see the similarity in certain group in Figure \ref{fig:coneptangio} it's relatively reliable estimate. Dispersal mode, leaf longevity, pollination mode and reproductive type also showed high phylogenetic signal in Table \ref{tab:lambda}, but be cautious that $\lambda$ for categorical traits might not be accurate. 
\item Be cautious that $\lambda$ might not be comparable among traits, not only because the way $\lambda$ is calculated for continuous traits and categorical traits are different, but also because $\lambda$ might depend on the data structure when sampling is uneven, take leaf longevity as an example in Figure \ref{fig:coneptangio},leaf longevity data is sparse and nested in \textit{Quercus.} (5/16). 
\end{enumerate}

\end{enumerate}

\newpage

\begin{table}[ht]
\centering
\resizebox{\textwidth}{!}{
<<echo=FALSE, results=tex>>=
angioTable <- xtable(angio_results, 
                 caption = "Phylogenetic generalized linear model results for angiosperm species. We modeled each trait separately with masting as a binary variable and traits as either categorical (Type column), where we report (Estimate column) the the difference in log-odds between a given level and its designated baseline reference level, or continuous, where we report the change in log-odds per unit increase of the predictor (Estimate column). We also report the standard error (SE), P-value (with P < 0.05 considered significant and marked with an asterisk next to the Predictor), Phylo $\alpha$, which represents the the phylogenetic signal in the residuals estimated for each trait, and the half-time (log(2)/$\alpha$), which represents the time required for the influence of ancestral states to decrease by half, where values less than 1 indicating relatively weak phylogenetic signal in the residuals.", 
                 label = "tab:regressionangio")
print(angioTable,
      type="latex",
      include.rownames=FALSE,
      floating=FALSE,
      sanitize.text.function = identity,
      sanitize.colnames.function = identity)
@
}
\caption{Phylogenetic generalized linear model results for angiosperm species. We modeled each trait separately with masting as a binary variable and traits as either categorical (Type column), where we report (Estimate column) the the difference in log-odds between a given level and its designated baseline reference level, or continuous, where we report the change in log-odds per unit increase of the predictor (Estimate column). We also report the standard error (SE), P-value (with P < 0.05 considered significant and marked with an asterisk next to the Predictor), Phylo $\alpha$, which represents the the phylogenetic signal in the residuals estimated for each trait, and the half-time (log(2)/$\alpha$), which represents the time required for the influence of ancestral states to decrease by half, where values less than 1 indicating relatively weak phylogenetic signal in the residuals.}
\label{tab:regressionangio}
\end{table}

\begin{table}[ht]
\centering
\resizebox{\textwidth}{!}{
<<echo=FALSE, results=tex>>=
conTable <- xtable(conifer_results, 
                 caption = "Phylogenetic generalized linear model results for gymnosperm species. We modeled each trait separately with masting as a binary variable and traits as either categorical (Type column), where we report (Estimate column) the the difference in log-odds between a given level and its designated baseline reference level, or continuous, where we report the change in log-odds per unit increase of the predictor (Estimate column). We also report the standard error (SE), P-value (with P < 0.05 considered significant and marked with an asterisk next to the Predictor), Phylo $\alpha$, which represents the the phylogenetic signal in the residuals estimated for each trait, and the half-time (log(2)/$\alpha$), which represents the time required for the influence of ancestral states to decrease by half, where values less than 1 indicating relatively weak phylogenetic signal in the residuals.", 
                 label = "tab:regressiongym")
print(conTable,
      type="latex",
      include.rownames=FALSE,
      floating=FALSE,
      sanitize.text.function = identity,
      sanitize.colnames.function = identity)
@
}
\caption{Phylogenetic generalized linear model results for gymnosperm species. We modeled each trait separately with masting as a binary variable and traits as either categorical (Type column), where we report (Estimate column) the the difference in log-odds between a given level and its designated baseline reference level, or continuous, where we report the change in log-odds per unit increase of the predictor (Estimate column). We also report the standard error (SE), P-value (with P < 0.05 considered significant and marked with an asterisk next to the Predictor), Phylo $\alpha$, which represents the the phylogenetic signal in the residuals estimated for each trait, and the half-time (log(2)/$\alpha$), which represents the time required for the influence of ancestral states to decrease by half, where values less than 1 indicating relatively weak phylogenetic signal in the residuals.}
\label{tab:regressiongym}
\end{table}

\begin{table}[ht]
\centering
\resizebox{\textwidth}{!}{
<<echo=FALSE, results=tex>>=
seedTable <- xtable(seed_results, 
                 caption = "Phylogenetic generalized linear model results for only seed weight for biotic-dispersed subgroup (both group included) and abiotic-dsipersed subgroup. We report the change in log-odds per unit increase of the predictor (Estimate column). We also report the standard error (SE), P-value (with P < 0.05 considered significant and marked with an asterisk next to the Predictor), Phylo $\alpha$, which represents the the phylogenetic signal in the residuals estimated for each trait, and the half-time (log(2)/$\alpha$), which represents the time required for the influence of ancestral states to decrease by half, where values less than 1 indicating relatively weak phylogenetic signal in the residuals.", 
                 label = "tab:regressionseed")
print(seedTable,
      type="latex",
      include.rownames=FALSE,
      floating=FALSE,
      sanitize.text.function = identity,
      sanitize.colnames.function = identity)
@
}
\caption{Phylogenetic generalized linear model results for only seed weight for biotic-dispersed subgroup (both group included) and abiotic-dsipersed subgroup. We report the change in log-odds per unit increase of the predictor (Estimate column). We also report the standard error (SE), P-value (with P < 0.05 considered significant and marked with an asterisk next to the Predictor), Phylo $\alpha$, which represents the the phylogenetic signal in the residuals estimated for each trait, and the half-time (log(2)/$\alpha$), which represents the time required for the influence of ancestral states to decrease by half, where values less than 1 indicating relatively weak phylogenetic signal in the residuals.}
\label{tab:regressionseed}
\end{table}

\begin{table}[ht]
\centering

<<echo=FALSE, results=tex>>=
lamTable <- xtable(lambda, 
                 caption = "Phylogenetic Signal (Pagel's lambda) for continous traits and multi-level categorical traits. lambda = 0 indicates no phylogenetic signal, trait districuted independent of the phylogeny; 0 < lambda < 1 means moderate phylogenetic signal, trait is partially structured by the phylogeny; lambda = 1 indicates strong phylogenetic signal, trait follows Brownian motion.", 
                 label = "tab:lambda")
print(lamTable,
      type="latex",
      include.rownames=FALSE,
      floating=FALSE)
@

\caption{Phylogenetic Signal (Pagel's $\lambda$) for continous traits and multi-level categorical traits. $\lambda$ = 0 indicates no phylogenetic signal, trait districuted independent of the phylogeny; 0 < $\lambda$ < 1 means moderate phylogenetic signal, trait is partially structured by the phylogeny; $\lambda$ = 1 indicates strong phylogenetic signal, trait follows Brownian motion.}
\label{tab:lambda}
\end{table}

\begin{table}[ht]
\centering
\resizebox{\textwidth}{!}{
<<echo=FALSE, results=tex>>=
dStatTable <- xtable(dStat, 
                 caption = "Phylogenetic Signal (D-statistic) for the phylogenetic signal of binary traits, with probabilities calculated under a random phylogenetic structure and under a Brownian motion phylogenetic structure. D = 1 indicates the trait is randomly distributed across the phylogeny; D = 0 indicates the trait follows a Brownian motion model; 0 < D < 1 indivates moderate phylogenetic signal; D < 0 indicates the trait is more clumped than expected under Brownian motion; and D > 1 indicates overdispersion. P random is the p-value for the null hypothesis that the trait is randomly distributed across the phylogeny (no phylogenetic signal), and P Brownian is the p-value for the null hypothesis that the trait follows a Brownian motion model (strong phylogenetic signal). A low p-value indicates rejection of the corresponding null hypothesis.", 
                 label = "tab:dstat")
print(dStatTable,
      type="latex",
      include.rownames=FALSE,
      floating=FALSE,
      sanitize.text.function = identity,
      sanitize.colnames.function = identity)
@
}
\caption{Phylogenetic Signal (D-statistic) for the phylogenetic signal of binary traits, with probabilities calculated under a random phylogenetic structure and under a Brownian motion phylogenetic structure. D = 1 indicates the trait is randomly distributed across the phylogeny; D = 0 indicates the trait follows a Brownian motion model; 0 < D < 1 indivates moderate phylogenetic signal; D < 0 indicates the trait is more clumped than expected under Brownian motion; and D > 1 indicates overdispersion. P random is the p-value for the null hypothesis that the trait is randomly distributed across the phylogeny (no phylogenetic signal), and P Brownian is the p-value for the null hypothesis that the trait follows a Brownian motion model (strong phylogenetic signal). A low p-value indicates rejection of the corresponding null hypothesis.}
\label{tab:dstat}
\end{table}


\end{enumerate}
\end{document}

When we know the phylogenetic results, we need to be cautious interpretating relationships between traits, it is hard to tease out traits from masting, which limits the inference)

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/quercusTree.pdf}
\caption{Phylogenetic tree for all \textit{Quercus.} species, \textit{Quercus.} species included in this study is color coded.}
\label{fig:quercus}
\end{figure}
% ------------------------------------------
\subsection{Data sparsity}
\begin{enumerate}
\item Data is strongly nested in phylogeny, and data is sparse (Figure \ref{fig:coneptangio}). We have to assume the sampling is even.
\item Among all the \textit{Quercus} species with well-resolved phylogeny (268), our dataset includes only 21 species, and only two of them are non-masting species (Figure \ref{fig:quercus}).

\end {enumerate}


