% !Rnw encoding = UTF-8
\documentclass{article}
\usepackage{graphicx}
\usepackage{Sweave}
\usepackage{float}
\usepackage[top=1.00in, bottom=1.0in, left=1.1in, right=1.1in]{geometry}

\title{Mast-Trait}
\author{Xiaomao Wang}
\date{\today}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

<<load-plots, eval=FALSE, echo=FALSE>>=
source("C:/PhD/Project/PhD_thesis/mast_trait/analyses/plottingSweave.R")
source("C:/PhD/Project/PhD_thesis/mast_trait/analyses/glm.R")
@

\section*{Hypotheses}
\subsection*{Predator Satiation}

\begin{itemize}
\item Dispersal mode: Animal-dispersed species may be more likely to mast, or
the mechanisms behind masting could differ depending on dispersal mode.
\end{itemize}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/dispersalmode.pdf}
\end{figure}
\newpage
\begin{itemize}
\item \textbf{Seed size:} Among animal-dispersed species, larger-seeded species might be more prone to masting.
\end{itemize}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/seedWeights.pdf}
\includegraphics[width=\textwidth]{../output/figures/seedSize.pdf}
\includegraphics[width=\textwidth]{../output/figures/fruitSize.pdf}
\end{figure}
\newpage
\begin{itemize}
\item \textbf{Seed dormancy:} Species with dormant seeds are expected to be more likely to mast.
\end{itemize}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/seedDormancy.pdf}
\end{figure}

\begin{itemize}
\item \textbf{Nutrient content:} Species with more nutritious seeds may be more likely to mast.
\end{itemize}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/oilContent.pdf}
\end{figure}
\newpage
% ------------------------------------------

\subsection*{Pollination Coupling}

\begin{itemize}
  \item Wind-pollinated species are expected to mast more frequently.
\end{itemize}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/pollination.pdf}
\end{figure}

\begin{itemize}
  \item Monoecious species may be more likely to mast.
\end{itemize}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/reproductiveType.pdf}
\end{figure}
\begin{itemize}
  \item Species with longer flowering periods may be more likely to mast.
\end{itemize}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/flowerDuration.pdf}
\end{figure}

% ------------------------------------------
\newpage
\subsection*{Resource Matching}

\begin{itemize}
  \item Leaf longevity: Species with long-lived leaves are expected to mast more frequently.
\end{itemize}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/leafLongevity.pdf}
\end{figure}

\begin{itemize}
  \item Drought tolerance: May go either way — tolerant species can accumulate resources; intolerant species respond to resource fluctuations.
\end{itemize}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/droughtTolerance.pdf}
\end{figure}
\newpage
% ------------------------------------------
\section*{Data visualization}
I calculated the mean and standard errors for the continuous traits in the raw dataset, with number of the data.
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/meanSE.pdf}
\end{figure}


Here's the version of raw data scattering on the plot
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/meanSERaw.pdf}
\end{figure}


\newpage
% ------------------------------------------
\section*{Results}
I ran the phyloglm, including the phylogeny variation.Here I reproted the direct model results in a table:
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/phyloglmResultsTable.pdf}
\end{figure}
\newpage
I also ran the common glm, using conifer and angiosperm as a fixed effect in the model, and I modified the results for better visualization:

For the categorical traits, I calculated the probability (of being a strong masting species) for each level:
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/glmCat.pdf}
\end{figure}
\newpage
For the continuous traits, I just presented the effect sizes, with the star indicating a p-value smaller than 0.05:
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{../output/figures/glmCon.pdf}
\end{figure}

\end{document}