\documentclass{article}
\usepackage{natbib}

\begin{document}
\SweaveOpts{concordance=TRUE}

\section{Method} %emw25May2026 -- Overall, this is a GREAT first draft; I think we can move quickly to a draft closer to final (or at least we can leave it for a while) ... more edits below, please work on these and pass back to me to review again. 
\subsection{Data Collection}
\subsubsection{Trait selection}
%emw25May2026  -- we need less passive voice below and we need to reverse the order of information -- put the reason generally FIRST ... I suggest you ask Victor about this, perhaps remind him of a book chapter I gave him to read (ask him for the book). 
We selected traits in the context of three hypotheses. For the predation satiation hypothesis we selected traits associated with seed attractiveness to predators and the potential for surviving in seed caches: seed weight, fruit size, oil content, dispersal mode and seed dormancy. For the pollination coupling hypothesis we aimed for traits related to higher pollination efficiency: pollination mode and reproductive type. For resource matching hypothesis we included traits responsible for higher flexibility in resource use under varying environmental conditions.
\subsubsection{Data scraping}
For our analyses, we obtained the full species list from the two volumes of \textit{Silvics of North America}\cite{burns1990silvics,burns1990silvics2} (hereafter referred as \textit{Silvics}). We extracted masting data primarily from \textit{Silvics}, with MASTREE used as a supplementary source when there was no description on the seed production patterns in \textit{Silvics}. Pollination mode and seed dispersal data were also obtained mainly from \textit{Silvics}. Seed weight data were collected from the Seed Information Database by the Society for Ecological Restoration. Seed dormancy data were gathered from \textit{Seeds} by Baskin and Baskin. Leaf longevity and oil content data were accessed through the TRY database. Fruit size and drought tolerance data were compiled from multiple sources, including: \textit{Silvics}, the USDA Fire Effects Information System, the USA National Phenology Network, and The Gymnosperm Database.

We defined masting based on qualitative description of seed production patterns. If the description said the species "have a good crop almost every year", we considered this species a non-masting species, whereas if the description said the species " have a good crop every several years or have irregular seed production", we considered this species as a masting species. 
%emw25May2026 -- I am not sure where the below goes but not in a topic sentence! I suggest you could contrast your approach with CV in one or two sentences at the end of the paragraph perhaps? (Though eventually we may have to move it to the discussion.)
%  instead of using the more commonly used coefficient of variation (CV),

%emw25May2026 -- sometimes you want to be repetitive in your sentence structure, but below it's just using up too many words without adding information ... I think here you need a topic sentence telling the reading this paragraph is about how you adjusted the data for analyses and then go through each one without repeating exact phrasing ... so (and this is NOT perfect, you need to work on it) something more like:  We adjusted our data on traits related to masting hypotheses so we could analyse it at the species level. For fruit size we .... We categorized several variables that spanned a large number of options into fewer categories; thus for pollination model we considered species as pollinated by wind, animal (bird, bat, or insect), or both and for drought tolerance as  low, moderate, or high.
%emw25May2026 --I would add: complete raw and adjusted data are published at KNB (then publish them before you submit). 
For fruit size data, we recorded the full range from the source, and took the mean value for further analyses. For pollination mode, we categorized it into wind, animal (bird, bat, or insect), or both. For seed dispersal mode, we categorized it into biotic (animal-dispersed), abiotic (wind-, gravity-, or water-dispersed), or both. For drought tolerance, we categorized it into low, moderate, or high. For leave longeivity, we standardized it to years.

In total, our dataset included 188 species, comprising 124 angiosperm species and 64 gymnosperm species. Among angiosperms, 79\% of species had masting data available, and masting species accounted for 52\%. Among gymnosperms, 95\% of species had masting data available, and 89\% species are masting species. %emw25May2026 -- May want to move to results?
\subsection{Statistical Analysis}
\subsubsection{Masting pattern and single trait}
%emw25May2026 -- ordering is off here also ... It should start: To analyze the relationship between masting pattern and individual traits ....
We used \texttt{phyloglm} function in the \texttt{phylolm} package (v. 2.6.2) to analyze the relationship between masting pattern and individual traits, treating masting as a binary response variable. To construct the phylogenetic tree, we verified all species names using the  \texttt{WorldFlora} package (v. 1.14-5) and updated all species names according to WCVP Backbone data (2025). We then constructed an ultrametric phylogenetic tree in R using the \texttt{phytools} (v. 2.4-4) and \texttt{ape} (v. 5.7-1) packages. We calculated the half-time using the equation $(\log(2)/\alpha)$ and compared it with the tree height (standardized to 1). This metric represents the time required for the influence of ancestral states to decrease by half.
\subsubsection{Masting pattern with a multivariate analysis}
%emw25May2026 -- ordering is off here also ... and you need to explain WHY you did this first. To supplement our single trait analyses (explained above) we also performed a multi....
Since most traits in our dataset were categorical, we selected non-metric multidimensional scaling (NMDS) for a multivariate analysis. We used the \texttt{metaMDS} function in the \texttt{vegan} (v. 2.7-1) package and tested both \(k = 2\) and \(k = 3\) and selected \(k = 3\) based on the lower stress score. We then plotted trait distributions on two panels (NMDS1 vs.\ NMDS2 and NMDS2 vs.\ NMDS3) to check for potential patterns.
\subsubsection{Phylogenetic signal for individual traits}
We calculated phylogenetic signal separately for each trait type. For binary traits, we calculated Fritz and Purvis' D-statistics using the function \texttt{phylo.d} in the \texttt{caper}  (v. 1.0.4) package. For continuous traits, we calculated the Pagel's $\lambda$ using the function \texttt{phylosig} in the \texttt{phytools} (v. 2.4-4) package. For categorical traits, we estimated the Pagel's $\lambda$ using the function \texttt{fitDiscrete} in the \texttt{geiger} (v. 2.0.11) package.

\bibliographystyle{besjournals}
\bibliography{mastTreeRef} 
\end{document}
